# Generated by Django 4.2 on 2023-04-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpracticentry',
            name='action',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
