# Generated by Django 4.2 on 2023-04-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_malpracticentry_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malpracticentry',
            old_name='action',
            new_name='actiontaken',
        ),
    ]
